openapi: 3.0.3
info:
  title: Galasa Runs Requests
  version: 0.15.0
servers:
- url: http://{server}:{port}
  variables:
    server:
      default: localhost
    port:
      default: "8080"
paths:
  /runs/{groupId}:
    get:
      operationId: getRunsByGroup
      parameters:
      - description: Run group ID can be any type of string value that is URL safe
        explode: false
        in: path
        name: groupId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestRuns'
          description: Returns all the runs for the groupid
      summary: Retrieve all active runs for a group id
    post:
      operationId: submitRunsByGroup
      parameters:
      - description: Run group ID can be any type of string value that is URL safe
        explode: false
        in: path
        name: groupId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestRunRequest'
        required: true
      responses:
        "200":
          description: Test Submitted
      summary: Submit a set of test runs for a group ID can be run multiple times
        against the same group ID, the new test runs will be appended
components:
  schemas:
    TestRuns:
      example:
        complete: true
        runs:
        - test: test
          queued: queued
          repo: repo
          type: type
          requestor: requestor
          local: true
          trace: true
          stream: stream
          name: name
          bundleName: bundleName
          obr: obr
          group: group
          testName: testName
          status: status
        - test: test
          queued: queued
          repo: repo
          type: type
          requestor: requestor
          local: true
          trace: true
          stream: stream
          name: name
          bundleName: bundleName
          obr: obr
          group: group
          testName: testName
          status: status
      properties:
        complete:
          type: boolean
        runs:
          items:
            $ref: '#/components/schemas/TestRun'
          type: array
    TestRun:
      example:
        test: test
        queued: queued
        repo: repo
        type: type
        requestor: requestor
        local: true
        trace: true
        stream: stream
        name: name
        bundleName: bundleName
        obr: obr
        group: group
        testName: testName
        status: status
      properties:
        name:
          description: The run name
          type: string
        type:
          description: The type of request, ie REQUEST, JENKINS, LOCAL
          type: string
        group:
          description: the group ID assigned to this run
          type: string
        test:
          description: the full test name in bundle/test format
          type: string
        bundleName:
          description: the bundle name
          type: string
        testName:
          description: the test class name
          type: string
        status:
          description: the current status of the run, ie allocated, starting, building
            etc
          type: string
        queued:
          description: when the test was queued
          type: string
        requestor:
          description: who requested the run
          type: string
        stream:
          description: the test stream the test should be loaded from
          type: string
        repo:
          description: the maven repositories to be used
          type: string
        obr:
          description: the obrs to be used
          type: string
        local:
          description: is this a local run
          type: boolean
        trace:
          description: has trace been requested
          type: boolean
    TestRunRequest:
      example:
        trace: true
        sharedEnvironmentRunName: sharedEnvironmentRunName
        requestorType: requestorType
        testStream: testStream
        classNames:
        - classNames
        - classNames
        sharedEnvironmentPhase: sharedEnvironmentPhase
        mavenRepository: mavenRepository
        overrides: '{}'
        requestor: requestor
        obr: obr
      properties:
        classNames:
          items:
            description: An array of bundle/test strings
            type: string
          type: array
        requestorType:
          description: The request type, normally REQUEST, JENKINS, can be others
          type: string
        requestor:
          description: The requestor, usually email address but doesnt need to be
          type: string
        testStream:
          description: The test stream to be used
          type: string
        obr:
          description: an overriding OBR
          type: string
        mavenRepository:
          description: an overriding maven repo
          type: string
        sharedEnvironmentPhase:
          description: The shared env phase, build or discard, for normal runs, null
          type: string
        sharedEnvironmentRunName:
          description: The shared env name,  for normal runs, null
          type: string
        overrides:
          description: Override properties
          type: object
        trace:
          description: enable trace
          type: boolean
